Import('env')

env = env.Clone()
thisDir = Dir('.').abspath
env.PrependENVPath('GOPATH', thisDir)

textproc = env.GoInstallPkg('textproc')
document = env.GoInstallPkg('local/document')
web = env.GoInstallPkg('web')
exe = env.GoInstall('pdfapp', [document, textproc, web])
Install(env.subst('$BINDIR'), exe)

def PhonyTargets(env = None, **kw):
     if not env: env = DefaultEnvironment()
     for target,action in kw.items():
         env.AlwaysBuild(env.Alias(target, [], action))

testDoc = env.Alias('TEST:DOC', document, 'go test local/document')
testWeb = env.Alias('TEST:WEB', web, 'go test web')
testApp = env.Alias('TEST:APP', exe, 'go test pdfapp')
env.AlwaysBuild(testDoc)
env.AlwaysBuild(testWeb)
env.AlwaysBuild(testApp)
testAll = env.Alias('TEST', [testDoc, testWeb, testApp])
 

